name: Test and Publish NuGet

# Trigger the workflow on push to master
on:
  push:
    branches:
      - "master"

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Test with dotnet
      working-directory: ./src
      run: dotnet test --configuration Release

    - name: Package NuGet
      working-directory: ./src
      run: dotnet pack --include-symbols --include-source --configuration Release

    - name: Upload NuGet Bufdio.Spice86
      working-directory: ./src/Bufdio.Spice86/bin/Release
      run: nuget push Bufdio.Spice86.6.4.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

    - name: Upload NuGet Spice86.Shared
      working-directory: ./src/Spice86.Shared/bin/Release
      run: nuget push Spice86.Shared.6.4.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

    - name: Upload NuGet Spice86.Logging
      working-directory: ./src/Spice86.Logging/bin/Release
      run: nuget push Spice86.Logging.6.4.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

    - name: Upload NuGet Spice86.Core
      working-directory: ./src/Spice86.Core/bin/Release
      run: nuget push Spice86.Core.6.4.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

    - name: Upload NuGet Spice86
      working-directory: ./src/Spice86/bin/Release
      run: nuget push Spice86.6.4.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate
